[SERVICE]
    Parsers_File  /fluent-bit/etc/parsers.conf
    Plugins_File  /fluent-bit/etc/plugins.conf

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        app_json
    Reserve_Data  Off
    Preserve_Key  Off

[OUTPUT]
    Name                       stackdriver_wif
    Match                      *
    project_id                 ${GCP_PROJECT_ID}
    log_id                     ${CLOUD_LOGGING_LOG_ID}
    resource                   global
    severity_key               level
    enable_identity_federation true
    aws_region                 ${AWS_REGION}
    project_number             ${GCP_PROJECT_NUMBER}
    pool_id                    ${WIF_POOL_ID}
    provider_id                ${WIF_PROVIDER_ID}
    google_service_account     ${GOOGLE_SERVICE_ACCOUNT}
