name: Workflow CI

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26.4"

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.12

      - name: Run actionlint
        run: actionlint

      - name: Check pinned actions
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          fix: "false"
          no_api: "true"

      - name: Install zizmor
        run: python3 -m pip install --user zizmor==1.26.1

      - name: Run zizmor
        env:
          GH_TOKEN: ${{ github.token }}
        run: '$HOME/.local/bin/zizmor .github/workflows'
